version: '3.1'

services:
  mysql_db:
    image: mysql:8
    container_name: mysql_local
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: stage
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret2
    volumes:
      - mysql_db:/var/lib/mysql
      - ./mysql_db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql_db:
    driver: local